# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AzPimCli < Formula
  desc "CLI utility for managing Azure PIM role assignments"
  homepage "https://github.com/mindmorass/az-pim-cli"
  version "1.11.1"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mindmorass/az-pim-cli/releases/download/v1.11.1/az-pim-cli-1.11.1-macos-x86_64.tar.gz"
      sha256 "ca387aa5564335f9ca8d108d88c6db2db83966a4b5aa373638051b3563da8aea"

      define_method(:install) do
        system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version} -X main.tag=v#{version}"), "."
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mindmorass/az-pim-cli/releases/download/v1.11.1/az-pim-cli-1.11.1-macos-arm64.tar.gz"
      sha256 "785ed167b646871c242967858545d376cf2f00755121f1f3236751b1d8b19067"

      define_method(:install) do
        system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version} -X main.tag=v#{version}"), "."
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mindmorass/az-pim-cli/releases/download/v1.11.1/az-pim-cli-1.11.1-linux-x86_64.tar.gz"
      sha256 "5642018641ad25a39e7c8b0dd1cf2f71d598465fc52cd102c44b22e92043ce33"
      define_method(:install) do
        system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version} -X main.tag=v#{version}"), "."
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mindmorass/az-pim-cli/releases/download/v1.11.1/az-pim-cli-1.11.1-linux-arm64.tar.gz"
      sha256 "368f498bfb33dffc84265a67adac959516204bc1d5b3d633626fde605da1fb30"
      define_method(:install) do
        system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version} -X main.tag=v#{version}"), "."
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/az-pim-cli version")
  end
end
